version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: core
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg_admin_1
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  collector:
    image: information-collector-service
    container_name: information-collector-service
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres

  csv-generator:
    image: csv-generator-service
    container_name: csv-generator-service
    build:
      context: ./../csv-generator-service
      dockerfile: ./../csv-generator-service/Dockerfile
    environment:
      OUTPUT_PATH: ${OUTPUT_PATH}
      TYPE: ${TYPE}
    volumes:
      - ${OUTPUT_PATH}:/app/output
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local